var ws = ''
var m_isConnectWS = false
var m_splitTag = '$*$'
var m_lastMessage = ''
var m_imageDataH = 0
var m_imageDataW = 0
var m_imageDataS = 0
var m_stopWait = false //同步等待
var m_closed = false //是否被关闭了
